### ISSUE TITLE
这是凉了嘛

### ISSUE THREAD

**Issue by lifeafter619** [anwenhu/zhixuewang#41]
AttributeError: 'TeacherAccount' object has no attribute 'get_self_mark'

这是啥子意思，不能用了嘛

**Comment by Leizhenpeng** [comment]
您好，我是雷圳鹏，已收到邮件，十分感谢！我会尽快回复。

**Comment by MasterYuan418** [comment]
教师账号没有get_self_mark这个函数，尝试使用StudentAccount（学生账号）
@lifeafter619

**Comment by Leizhenpeng** [comment]
您好，我是雷圳鹏，已收到邮件，十分感谢！我会尽快回复。
