### ISSUE TITLE
学校未开放查询权限给学生

### ISSUE THREAD

**Issue by IAMNAVY** [anwenhu/zhixuewang#51]
若学校未开放成绩查询全给给学生，有办法查到具体成绩吗？

**Comment by MasterYuan418** [comment]
@SkinCrab 你这个情况和我有点类似，我说一下我的解决方案：
1. 通过教师端查询成绩（简单方便）
2. 通过教师端获取`examid`和`subjectId`，然后手动给学生端传参。

**Comment by moxisuki** [comment]
@MasterYuan418 
教师端如何获取`examid`呢

**Comment by MasterYuan418** [comment]
> @MasterYuan418 教师端如何获取`examid`呢

看了一下，貌似教师端还真不能获取`examid`。不过你可以登上智学网的web端看

**Comment by MasterYuan418** [comment]
@moxisuki  你好，新PR #69 已经可以在教师端使用`get_exams`获取考试了，里面包含`examid`。

**Comment by moxisuki** [comment]
> @moxisuki  你好，新PR #69 已经可以在教师端使用`get_exams`获取考试了，里面包含`examid`。

好！赞
