### ISSUE TITLE
原始分与赋分分数的区别

### ISSUE THREAD

**Issue by SherkeyXD** [anwenhu/zhixuewang#58]
新高考地区存在赋分这一机制，随之而来的也有原始分和赋分分数的差别问题
如何判断查到的分数是哪一个？

**Comment by SherkeyXD** [comment]
在赋分成绩出来之后好像没法直接查原始分

**Comment by anwenhu** [comment]
学生账号查到的应该就是赋分, 原始分不能直接查到
