### ISSUE TITLE
教师端无法登录

### ISSUE THREAD

**Issue by amakerlife** [anwenhu/zhixuewang#70]
通过 login_teacher 和 login_teacher_id 两种方式均无法登录，以下是可复现问题的代码：

```python
from zhixuewang import login_teacher
if __name__ == "__main__":
    uname = str(input("UserName: "))
    upwd = str(input("Password: "))
    teacher = login_teacher(uname, upwd)
```

以及报错：

```
Traceback (most recent call last):
  File "test.py", line 5, in <module>
    teacher = login_teacher(uname, upwd)
  File "Python\Python311\site-packages\zhixuewang\account.py", line 100, in login_teacher
    return teacher.set_base_info()
  File "Python\Python311\site-packages\zhixuewang\teacher\teacher.py", line 79, in set_base_info
    adv_result["grade"]["name"], code=adv_result["grade"]["code"]
TypeError: 'NoneType' object is not subscriptable
```

**Comment by MasterYuan418** [comment]
@amakerlife 你好，你是怎么解决这个问题的？我看报错信息是定位在高级信息的，发生了啥

**Comment by amakerlife** [comment]
@MasterYuan418 刚才放服务器上跑的旧版库可以，就以为是本地的问题

**Comment by aquamarine5** [comment]
蹲一个solution

**Comment by MasterYuan418** [comment]
> 蹲一个solution

无法登录吗？可以尝试更新到`1.1.10`，至少我本地这个版本是能够正常登录的

**Comment by aquamarine5** [comment]
> > 蹲一个solution
> 
> 无法登录吗？可以尝试更新到`1.1.10`，至少我本地这个版本是能够正常登录的

更新了之后正常了 thx😊

**Comment by amakerlife** [comment]
> 

为什么我这个还不行啊😂

![image](https://github.com/anwenhu/zhixuewang-python/assets/64350662/435e9aa3-1cd9-4456-af74-41cb345010b7)

**Comment by aquamarine5** [comment]
把梯子关了可能行🤔刚才试了试发现偶尔会拒绝连接 把梯子关了就没事了

**Comment by MasterYuan418** [comment]
> > 
> 
> 为什么我这个还不行啊😂
> 
> ![image](https://user-images.githubusercontent.com/64350662/256976969-435e9aa3-1cd9-4456-af74-41cb345010b7.png)

方便给出你的代码吗？我这边的测试代码是
```python
from zhxuewang import *
teacher=login("???","???")
teacher.currentSchool
```
我这边是可以正常返回的。或者你可以在`teacher.py`第69行之前加一行print看下回传了什么
```diff python
def set_base_info(self):
...
        advanced_info = self._session.get(
            Url.GET_ADVANCED_INFORMATION_URL,
            headers={
                "referer": "https://www.zhixue.com/paperfresh/dist/assets/expertPaper.html"
            },
        )
+     print(advanced_info.json()["result"])
        adv_result = advanced_info.json()["result"]
```

**Comment by amakerlife** [comment]
> > > 
> > 
> > 
> > 为什么我这个还不行啊😂
> > ![image](https://user-images.githubusercontent.com/64350662/256976969-435e9aa3-1cd9-4456-af74-41cb345010b7.png)
> 
> 方便给出你的代码吗？我这边的测试代码是
> 
> ```python
> from zhxuewang import *
> teacher=login("???","???")
> teacher.currentSchool
> ```
> 
> 我这边是可以正常返回的。或者你可以在`teacher.py`第69行之前加一行print看下回传了什么
> 
> ```diff
> def set_base_info(self):
> ...
>         advanced_info = self._session.get(
>             Url.GET_ADVANCED_INFORMATION_URL,
>             headers={
>                 "referer": "https://www.zhixue.com/paperfresh/dist/assets/expertPaper.html"
>             },
>         )
> +     print(advanced_info.json()["result"])
>         adv_result = advanced_info.json()["result"]
> ```

应该是账号的问题，刚发现我那个教师账号被冻结了。

前天还登过网页版，今天一看要申请解冻。

![image](https://github.com/anwenhu/zhixuewang-python/assets/64350662/8f46691d-419b-4472-9807-dc7da3a4a6fd)

**Comment by amakerlife** [comment]
不对，被冻结应该也能看，返回值正常。🤔

```
{'id': '??', 'loginName': '??', 'name': '??', 'mobile': '??', 'school': {'id': '??', 'name': '??', 'eduSys': 'SIX_THREE', 'phases': [{'code': '05', 'name': '高中'}]}, 'organType': 'SCHOOL', 'organ': None, 'province': {'code': '370000', 'name': '山东省', 'level': None, 'id': '1489'}, 'city': {'code': '371400', 'name': '德州市', 'level': None, 'id': '1621'}, 'superAdminType': None, 'curPSTeachers': [], 'roles': [{'eName': 'teacher', 'cName': '老师', 'roleId': '??'}], 'virtualSch': False, 'regionSchoolId': None, 'schoolTypes': [], 'curPhaseCode': '05', 'curPhase': {'code': '05', 'name': '高中'}, 'curSubjectCode': '01', 'curSubject': {'code': '01', 'name': '语文', 'sort': 1}, 'curMappingSubjectCode': '01', 'curMappingSubject': {'code': '01', 'name': '语文', 'sort': 1}, 'grade': None, 'bookVersion': {'code': '272', 'name': '人教版（新课标）'}, 'textBookVersion': {'code': '1901050101-2313', 'name': '高中必修上册'}, 'packageType': 'BASIC', 'packagePhases': ['05', '04'], 'curTeachingSubjects': [], 'curTeachingGradeSubjects': [], 'phaseSubjects': [], 'curTeachingGrades': [], 'authorityTypes': ['NOT_SHOW_SET_HOMEWORK', 'SIMPLE_PAPER_MANAGE'], 'phaseAndSubjects': [{'phase': {'code': '05', 'name': '高中'}, 'subjects': [{'code': '01', 'name': '语文', 'sort': 1}, {'code': '02', 'name': '数学', 'sort': 2}, {'code': '03', 'name': '英语', 'sort': 3}, {'code': '05', 'name': '物理', 'sort': 4}, {'code': '06', 'name': '化学', 'sort': 5}, {'code': '13', 'name': '生物', 'sort': 6}, {'code': '27', 'name': '政治', 'sort': 7}, {'code': '12', 'name': '历史', 'sort': 8}, {'code': '14', 'name': '地理', 'sort': 9}, {'code': '26', 'name': '信息技术', 'sort': 15}, {'code': '102', 'name': '通用技术', 'sort': 999}, {'code': '103', 'name': '思想政治', 'sort': 999}], 'grades': [{'code': '10', 'name': '高一'}, {'code': '11', 'name': '高二'}, {'code': '12', 'name': '高三'}]}, {'phase': {'code': '04', 'name': '初中'}, 'subjects': [{'code': '01', 'name': '语文', 'sort': 1}, {'code': '02', 'name': '数学', 'sort': 2}, {'code': '03', 'name': '英语', 'sort': 3}, {'code': '05', 'name': '物理', 'sort': 4}, {'code': '06', 'name': '化学', 'sort': 5}, {'code': '13', 'name': '生物', 'sort': 6}, {'code': '27', 'name': '政治', 'sort': 7}, {'code': '12', 'name': '历史', 'sort': 8}, {'code': '14', 'name': '地理', 'sort': 9}, {'code': '19', 'name': '科学', 'sort': 12}, {'code': '08', 'name': '历史与社会', 'sort': 13}, {'code': '239', 'name': '道德与法治', 'sort': 14}, {'code': '26', 'name': '信息技术', 'sort': 15}], 'grades': [{'code': '07', 'name': '七年级'}, {'code': '08', 'name': '八年级'}, {'code': '09', 'name': '九年级'}]}], 'reasonIndex': None, 'vueState': True, 'mylibVueState': True, '54EduSys': False, 'schoolId': '??', 'curTeachingGradeCodes': [], 'organId': '??', 'forbiddenRole': False, 'domain': False}
Traceback (most recent call last):
  File "C:\Users\yuyan\Desktop\test.py", line 2, in <module>
    teacher=login("tch303573","111111")
  File "D:\Program Files\Python311\Lib\site-packages\zhixuewang\account.py", line 145, in login
    return TeacherAccount(session).set_base_info()
  File "D:\Program Files\Python311\Lib\site-packages\zhixuewang\teacher\teacher.py", line 80, in set_base_info
    adv_result["grade"]["name"], code=adv_result["grade"]["code"]
TypeError: 'NoneType' object is not subscriptable
```

**Comment by amakerlife** [comment]
不对，被冻结应该也能看，返回值正常。🤔

```
{'id': '??', 'loginName': '??', 'name': '??', 'mobile': '??', 'school': {'id': '??', 'name': '??', 'eduSys': 'SIX_THREE', 'phases': [{'code': '05', 'name': '高中'}]}, 'organType': 'SCHOOL', 'organ': None, 'province': {'code': '370000', 'name': '山东省', 'level': None, 'id': '1489'}, 'city': {'code': '371400', 'name': '德州市', 'level': None, 'id': '1621'}, 'superAdminType': None, 'curPSTeachers': [], 'roles': [{'eName': 'teacher', 'cName': '老师', 'roleId': '??'}], 'virtualSch': False, 'regionSchoolId': None, 'schoolTypes': [], 'curPhaseCode': '05', 'curPhase': {'code': '05', 'name': '高中'}, 'curSubjectCode': '01', 'curSubject': {'code': '01', 'name': '语文', 'sort': 1}, 'curMappingSubjectCode': '01', 'curMappingSubject': {'code': '01', 'name': '语文', 'sort': 1}, 'grade': None, 'bookVersion': {'code': '272', 'name': '人教版（新课标）'}, 'textBookVersion': {'code': '1901050101-2313', 'name': '高中必修上册'}, 'packageType': 'BASIC', 'packagePhases': ['05', '04'], 'curTeachingSubjects': [], 'curTeachingGradeSubjects': [], 'phaseSubjects': [], 'curTeachingGrades': [], 'authorityTypes': ['NOT_SHOW_SET_HOMEWORK', 'SIMPLE_PAPER_MANAGE'], 'phaseAndSubjects': [{'phase': {'code': '05', 'name': '高中'}, 'subjects': [{'code': '01', 'name': '语文', 'sort': 1}, {'code': '02', 'name': '数学', 'sort': 2}, {'code': '03', 'name': '英语', 'sort': 3}, {'code': '05', 'name': '物理', 'sort': 4}, {'code': '06', 'name': '化学', 'sort': 5}, {'code': '13', 'name': '生物', 'sort': 6}, {'code': '27', 'name': '政治', 'sort': 7}, {'code': '12', 'name': '历史', 'sort': 8}, {'code': '14', 'name': '地理', 'sort': 9}, {'code': '26', 'name': '信息技术', 'sort': 15}, {'code': '102', 'name': '通用技术', 'sort': 999}, {'code': '103', 'name': '思想政治', 'sort': 999}], 'grades': [{'code': '10', 'name': '高一'}, {'code': '11', 'name': '高二'}, {'code': '12', 'name': '高三'}]}, {'phase': {'code': '04', 'name': '初中'}, 'subjects': [{'code': '01', 'name': '语文', 'sort': 1}, {'code': '02', 'name': '数学', 'sort': 2}, {'code': '03', 'name': '英语', 'sort': 3}, {'code': '05', 'name': '物理', 'sort': 4}, {'code': '06', 'name': '化学', 'sort': 5}, {'code': '13', 'name': '生物', 'sort': 6}, {'code': '27', 'name': '政治', 'sort': 7}, {'code': '12', 'name': '历史', 'sort': 8}, {'code': '14', 'name': '地理', 'sort': 9}, {'code': '19', 'name': '科学', 'sort': 12}, {'code': '08', 'name': '历史与社会', 'sort': 13}, {'code': '239', 'name': '道德与法治', 'sort': 14}, {'code': '26', 'name': '信息技术', 'sort': 15}], 'grades': [{'code': '07', 'name': '七年级'}, {'code': '08', 'name': '八年级'}, {'code': '09', 'name': '九年级'}]}], 'reasonIndex': None, 'vueState': True, 'mylibVueState': True, '54EduSys': False, 'schoolId': '??', 'curTeachingGradeCodes': [], 'organId': '??', 'forbiddenRole': False, 'domain': False}
Traceback (most recent call last):
  File "C:\Users\??\Desktop\test.py", line 2, in <module>
    teacher=login("??","??")
  File "D:\Program Files\Python311\Lib\site-packages\zhixuewang\account.py", line 145, in login
    return TeacherAccount(session).set_base_info()
  File "D:\Program Files\Python311\Lib\site-packages\zhixuewang\teacher\teacher.py", line 80, in set_base_info
    adv_result["grade"]["name"], code=adv_result["grade"]["code"]
TypeError: 'NoneType' object is not subscriptable
```

?? 处为原本正常信息。

**Comment by MasterYuan418** [comment]
> 不对，被冻结应该也能看，返回值正常。🤔
> 
> ```
> {'id': '??', 'loginName': '??', 'name': '??', 'mobile': '??', 'school': {'id': '??', 'name': '??', 'eduSys': 'SIX_THREE', 'phases': [{'code': '05', 'name': '高中'}]}, 'organType': 'SCHOOL', 'organ': None, 'province': {'code': '370000', 'name': '山东省', 'level': None, 'id': '1489'}, 'city': {'code': '371400', 'name': '德州市', 'level': None, 'id': '1621'}, 'superAdminType': None, 'curPSTeachers': [], 'roles': [{'eName': 'teacher', 'cName': '老师', 'roleId': '??'}], 'virtualSch': False, 'regionSchoolId': None, 'schoolTypes': [], 'curPhaseCode': '05', 'curPhase': {'code': '05', 'name': '高中'}, 'curSubjectCode': '01', 'curSubject': {'code': '01', 'name': '语文', 'sort': 1}, 'curMappingSubjectCode': '01', 'curMappingSubject': {'code': '01', 'name': '语文', 'sort': 1}, 'grade': None, 'bookVersion': {'code': '272', 'name': '人教版（新课标）'}, 'textBookVersion': {'code': '1901050101-2313', 'name': '高中必修上册'}, 'packageType': 'BASIC', 'packagePhases': ['05', '04'], 'curTeachingSubjects': [], 'curTeachingGradeSubjects': [], 'phaseSubjects': [], 'curTeachingGrades': [], 'authorityTypes': ['NOT_SHOW_SET_HOMEWORK', 'SIMPLE_PAPER_MANAGE'], 'phaseAndSubjects': [{'phase': {'code': '05', 'name': '高中'}, 'subjects': [{'code': '01', 'name': '语文', 'sort': 1}, {'code': '02', 'name': '数学', 'sort': 2}, {'code': '03', 'name': '英语', 'sort': 3}, {'code': '05', 'name': '物理', 'sort': 4}, {'code': '06', 'name': '化学', 'sort': 5}, {'code': '13', 'name': '生物', 'sort': 6}, {'code': '27', 'name': '政治', 'sort': 7}, {'code': '12', 'name': '历史', 'sort': 8}, {'code': '14', 'name': '地理', 'sort': 9}, {'code': '26', 'name': '信息技术', 'sort': 15}, {'code': '102', 'name': '通用技术', 'sort': 999}, {'code': '103', 'name': '思想政治', 'sort': 999}], 'grades': [{'code': '10', 'name': '高一'}, {'code': '11', 'name': '高二'}, {'code': '12', 'name': '高三'}]}, {'phase': {'code': '04', 'name': '初中'}, 'subjects': [{'code': '01', 'name': '语文', 'sort': 1}, {'code': '02', 'name': '数学', 'sort': 2}, {'code': '03', 'name': '英语', 'sort': 3}, {'code': '05', 'name': '物理', 'sort': 4}, {'code': '06', 'name': '化学', 'sort': 5}, {'code': '13', 'name': '生物', 'sort': 6}, {'code': '27', 'name': '政治', 'sort': 7}, {'code': '12', 'name': '历史', 'sort': 8}, {'code': '14', 'name': '地理', 'sort': 9}, {'code': '19', 'name': '科学', 'sort': 12}, {'code': '08', 'name': '历史与社会', 'sort': 13}, {'code': '239', 'name': '道德与法治', 'sort': 14}, {'code': '26', 'name': '信息技术', 'sort': 15}], 'grades': [{'code': '07', 'name': '七年级'}, {'code': '08', 'name': '八年级'}, {'code': '09', 'name': '九年级'}]}], 'reasonIndex': None, 'vueState': True, 'mylibVueState': True, '54EduSys': False, 'schoolId': '??', 'curTeachingGradeCodes': [], 'organId': '??', 'forbiddenRole': False, 'domain': False}
> Traceback (most recent call last):
>   File "C:\Users\??\Desktop\test.py", line 2, in <module>
>     teacher=login("??","??")
>   File "D:\Program Files\Python311\Lib\site-packages\zhixuewang\account.py", line 145, in login
>     return TeacherAccount(session).set_base_info()
>   File "D:\Program Files\Python311\Lib\site-packages\zhixuewang\teacher\teacher.py", line 80, in set_base_info
>     adv_result["grade"]["name"], code=adv_result["grade"]["code"]
> TypeError: 'NoneType' object is not subscriptable
> ```
> 
> ?? 处为原本正常信息。

![图片](https://github.com/anwenhu/zhixuewang-python/assets/58651976/b9c2111d-62af-45d9-aeb8-cf46ba52ad75)
你这个回传`Grade`就是空的，可能是这个教师账号没有任教学科

**Comment by amakerlife** [comment]
> > 不对，被冻结应该也能看，返回值正常。🤔
> > ```
> > {'id': '??', 'loginName': '??', 'name': '??', 'mobile': '??', 'school': {'id': '??', 'name': '??', 'eduSys': 'SIX_THREE', 'phases': [{'code': '05', 'name': '高中'}]}, 'organType': 'SCHOOL', 'organ': None, 'province': {'code': '370000', 'name': '山东省', 'level': None, 'id': '1489'}, 'city': {'code': '371400', 'name': '德州市', 'level': None, 'id': '1621'}, 'superAdminType': None, 'curPSTeachers': [], 'roles': [{'eName': 'teacher', 'cName': '老师', 'roleId': '??'}], 'virtualSch': False, 'regionSchoolId': None, 'schoolTypes': [], 'curPhaseCode': '05', 'curPhase': {'code': '05', 'name': '高中'}, 'curSubjectCode': '01', 'curSubject': {'code': '01', 'name': '语文', 'sort': 1}, 'curMappingSubjectCode': '01', 'curMappingSubject': {'code': '01', 'name': '语文', 'sort': 1}, 'grade': None, 'bookVersion': {'code': '272', 'name': '人教版（新课标）'}, 'textBookVersion': {'code': '1901050101-2313', 'name': '高中必修上册'}, 'packageType': 'BASIC', 'packagePhases': ['05', '04'], 'curTeachingSubjects': [], 'curTeachingGradeSubjects': [], 'phaseSubjects': [], 'curTeachingGrades': [], 'authorityTypes': ['NOT_SHOW_SET_HOMEWORK', 'SIMPLE_PAPER_MANAGE'], 'phaseAndSubjects': [{'phase': {'code': '05', 'name': '高中'}, 'subjects': [{'code': '01', 'name': '语文', 'sort': 1}, {'code': '02', 'name': '数学', 'sort': 2}, {'code': '03', 'name': '英语', 'sort': 3}, {'code': '05', 'name': '物理', 'sort': 4}, {'code': '06', 'name': '化学', 'sort': 5}, {'code': '13', 'name': '生物', 'sort': 6}, {'code': '27', 'name': '政治', 'sort': 7}, {'code': '12', 'name': '历史', 'sort': 8}, {'code': '14', 'name': '地理', 'sort': 9}, {'code': '26', 'name': '信息技术', 'sort': 15}, {'code': '102', 'name': '通用技术', 'sort': 999}, {'code': '103', 'name': '思想政治', 'sort': 999}], 'grades': [{'code': '10', 'name': '高一'}, {'code': '11', 'name': '高二'}, {'code': '12', 'name': '高三'}]}, {'phase': {'code': '04', 'name': '初中'}, 'subjects': [{'code': '01', 'name': '语文', 'sort': 1}, {'code': '02', 'name': '数学', 'sort': 2}, {'code': '03', 'name': '英语', 'sort': 3}, {'code': '05', 'name': '物理', 'sort': 4}, {'code': '06', 'name': '化学', 'sort': 5}, {'code': '13', 'name': '生物', 'sort': 6}, {'code': '27', 'name': '政治', 'sort': 7}, {'code': '12', 'name': '历史', 'sort': 8}, {'code': '14', 'name': '地理', 'sort': 9}, {'code': '19', 'name': '科学', 'sort': 12}, {'code': '08', 'name': '历史与社会', 'sort': 13}, {'code': '239', 'name': '道德与法治', 'sort': 14}, {'code': '26', 'name': '信息技术', 'sort': 15}], 'grades': [{'code': '07', 'name': '七年级'}, {'code': '08', 'name': '八年级'}, {'code': '09', 'name': '九年级'}]}], 'reasonIndex': None, 'vueState': True, 'mylibVueState': True, '54EduSys': False, 'schoolId': '??', 'curTeachingGradeCodes': [], 'organId': '??', 'forbiddenRole': False, 'domain': False}
> > Traceback (most recent call last):
> >   File "C:\Users\??\Desktop\test.py", line 2, in <module>
> >     teacher=login("??","??")
> >   File "D:\Program Files\Python311\Lib\site-packages\zhixuewang\account.py", line 145, in login
> >     return TeacherAccount(session).set_base_info()
> >   File "D:\Program Files\Python311\Lib\site-packages\zhixuewang\teacher\teacher.py", line 80, in set_base_info
> >     adv_result["grade"]["name"], code=adv_result["grade"]["code"]
> > TypeError: 'NoneType' object is not subscriptable
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ?? 处为原本正常信息。
> 
> ![图片](https://user-images.githubusercontent.com/58651976/256978907-b9c2111d-62af-45d9-aeb8-cf46ba52ad75.png) 你这个回传`Grade`就是空的，可能是这个教师账号没有任教学科

那就是这版更新的问题，把 Grade 临时改成空就行了。https://github.com/anwenhu/zhixuewang-python/commit/67e42f4570f6c4c88b67d6c0fb13422c115453ed
