### ISSUE TITLE
获取student等寄了？

### ISSUE THREAD

**Issue by zhangxu1233** [anwenhu/zhixuewang#85]
<img width="940" alt="image" src="https://github.com/anwenhu/zhixuewang-python/assets/94178739/e147b955-87b1-4735-9027-bef280d9ad06">
<img width="955" alt="image" src="https://github.com/anwenhu/zhixuewang-python/assets/94178739/4e0e8b4e-78c1-4a37-b583-8f7aa7c9d8f6">

这是寄了？

**Comment by anwenhu** [comment]
第一个是因为直接print数组不会调用StuPerson类的__str__方法, 看到的就是id, 用for循环遍历打印(print)数组每一个元素就是正常的.
第二个是在获取zhixuewang一个接口时返回数据不符合要求, 具体得看返回内容.
