### ISSUE TITLE
无法登录

### ISSUE THREAD

**Issue by ACaiCat** [anwenhu/zhixuewang#90]
已确认登录的账号密码均是正确的，可能是登录的API有所改动
![image](https://github.com/anwenhu/zhixuewang-python/assets/62058454/4e1650de-bb8f-498a-a414-d63f93fca4c8)

**Comment by anwenhu** [comment]
已确认是接口变动, 现在必须得把通过滑动验证码的相关数据传进去, 找了下没找到绕不开那个滑动验证码的方法了, 这种api类接口也不可能说做验证码的动画什么的, 只能说让用户手动登录后填cookie了(比如selenium开个浏览器让用户填完后把cookie保存到程序内), 后面可能就是改成这么做了

**Comment by haorwen** [comment]
可以暂时用cookie方法来登录[#91](https://github.com/anwenhu/zhixuewang-python/pull/91)

**Comment by ACaiCat** [comment]
已经用上了，感谢！
